### ISSUE TITLE
High-performance bots are not participating in waiting room

### ISSUE THREAD

**Issue by davisagli** [Dallinger/Dallinger#1004]
High-performance bots (such as the new Griduniverse ones) are creating a participant immediately rather than waiting for a quorum. This is most noticeable when running an experiment mixing bots and other recruitment. If the real participants don't show up right away, they may find that the bots have already completed the game.

**Comment by jessesnyder** [comment]
Questions:

1. What happens when a regular player tries to play?
    1. Views /waiting, which calls dallinger.createParticipant()
        1. Creates participant right away
        2. Only goes to /grid when quorum reached
            1. Learns about quorum by subscribing to “/chat?channel=quorum”
2. What happens when a High Performance Bot tries to play?
    1. Subscribes to ‘griduniverse’ channel 
    2. Sends ‘connect’ message to ‘griduniverse_ctrl’ channel, which creates a Participant
    3. As soon as a ‘state’ message is received from the channel with a ‘remaining_time’ attribute, the bot will start interacting with the grid

Ideas:

1. At first, don’t worry about dealing with scenario where quorum is already met when Participant is created
2. Check for ‘quorum’ key in result in “sign_up()”
3. If there’s a quorum, subscribe to the channel and loop on a check

Problems:
1. All bots have signed up (created participants) and quorum messages sent before any one of them has a chance to start listening to the channel

Solution:
1. Subscribe to quorum channel at the beginning of sign_up(), before the participant is created.

**Comment by vlall** [comment]
Fixed: https://github.com/Dallinger/Dallinger/pull/1027
