### ISSUE TITLE
Demo - Rogers experiment bug

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1547]
The experiment works for many participants, yet after some recruiment cycles (depending on initial parameters specified), the participants start to get routed directly to questionnaire, after hitting Begin button

The "Thanks for accepting this HIT." page does not move to "Thanks for your participation" page after the questionnaire is submitted.

Console:
```
"POST /participant/37Q87P/GGCRER/I13GIN/debug?fingerprint_hash=undefined&recruiter=undefined
```

**Comment by jessesnyder** [comment]
Ran to completion for me, and all partcipants have all values:
```
 id |       creation_time        | property1 | property2 | property3 | property4 | property5 | failed | time_of_death | details |    type     |         fingerprint_hash         | recruiter_id | worker_id | assignment_id |   unique_id   | hit_id | mode  |          end_time          | base_pay | bonus |  status
----+----------------------------+-----------+-----------+-----------+-----------+-----------+--------+---------------+---------+-------------+----------------------------------+--------------+-----------+---------------+---------------+--------+-------+----------------------------+----------+-------+----------
  1 | 2019-01-08 10:32:39.98531  |           |           |           |           |           | f      |               | {}      | participant | 7f928b7a33383dcb06bf50b5cc131fd1 | hotair       | VLVS47    | 6C83KY        | VLVS47:6C83KY | Q6MCIQ | debug | 2019-01-08 10:35:02.088967 |        1 |   0.4 | approved
  2 | 2019-01-08 10:35:09.294917 |           |           |           |           |           | f      |               | {}      | participant | 7f928b7a33383dcb06bf50b5cc131fd1 | hotair       | 5V0Z9G    | 1A4ICN        | 5V0Z9G:1A4ICN | RLSMBD | debug | 2019-01-08 10:38:15.039613 |        1 |     1 | approved
  3 | 2019-01-08 10:38:24.163436 |           |           |           |           |           | f      |               | {}      | participant | 7f928b7a33383dcb06bf50b5cc131fd1 | hotair       | NFF0JN    | N8V5B4        | NFF0JN:N8V5B4 | HT9J49 | debug | 2019-01-08 10:38:54.025923 |        1 |     0 | approved
```

**Comment by jessesnyder** [comment]
@thomasmorgan I think I've found an off-by-one error in recruitment in the Rogers demo, which I'll try to explain with an example.

Say you want to run 2 generations of 2 participants (so, 4 participants in all). The experiment will create 4 DiscreetGenerational networks, passing a value of 2 for both `generations` and `generation_size`, and also specifying `initial_source=True`. This results in networks with a `max_size` of 5 (`2 * 2 + 1`). This _would_ be enough to hold a initial Source plus 4 participant Nodes, except that the experiment also adds a `RogersEnvironment` to each network, which eats up a spot. 

When the experiment runs, the first generation works fine, adding a participant Node to each network, but bringing each networks count up to 4. When the generation finishes, another _pair_ of participants in recruited (`self.recruiter.recruit(n=self.generation_size)`). The first participant in the pair uses the final slot in each network; the second participant triggers an error when trying to add their participant Node, because the networks are all full.

Any ideas on how to address this? I'm not sure if `max_size` could simply be incremented by 1 when the RogersEnvironments are added(?)

**Comment by witekdev** [comment]
This has been resolved and the demo has been tested to work in debug mode.
