### ISSUE TITLE
Automated compensation -- 8 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2028]
As a requester, we would like to have a command-line tool that efficiently credits a given Turker with a given amount of money. Something like:

credit_turker <worker_id> <amount_in_dollars>

Our current process is inefficient and manual, it involves assigning a qualification to the participant and creating a HIT that only they can see. 

The new command line tool could do something like this:
(a)  Create a custom HIT for the participant that only they can see (using a qualification), that gives them $XXX once they complete it.
(b) Send an email to the participant with the link to this compensation HIT.

**Comment by jessesnyder** [comment]
@jacobyn @pmcharrison I've made the changes to the MTurkService to allow adding the new command. Since it's a good time for me to pause, I wanted to just show a sketch of the command itself to verify that it makes sense to you:

```
$ dallinger credit_turker --worker 12345 --dollars 10
Would credit worker ID 12345 $10 in MTurk production.

$ dallinger credit_turker --worker 12345 --dollars 10 --notify
Would credit worker ID 12345 $10 in MTurk production and email them.

$ dallinger credit_turker --worker 12345 --dollars 10 --notify --sandbox
Would credit worker ID 12345 $10 in MTurk sandbox and email them.
```

Perhaps emailing should be the default? It now occurs to me that we probably need to provide the email address as an argument.

**Comment by pmcharrison** [comment]
Looking great, Jesse! I think it's a good idea to notify as default. When we manually bonus workers, I remember something about being able to provide a custom message, would we able to hook onto the same thing here, to avoid having to specify the email address manually? Maybe I'm misremembering though.

**Comment by jessesnyder** [comment]
Thanks, @pmcharrison cc @jacobyn  As I understand it, a crucial difference here is that we don't have an existing HIT and Assignment, which is the pathway by which we can email a worker when they're granted a bonus. We can maybe still send a message when they complete the compensation HIT, but my understanding was that you also wanted to automate sending them an email when the HIT was ready, and how to find it on MTurk. I'm hoping we don't have to actually launch anything on Heroku, and can just create a HIT on MTurk only, but when I try this I'm only able to return the HIT after accepting it; not submit it. What is your process for doing this manually?

**Comment by jessesnyder** [comment]
I think I found my answers about your current process in the Frankfurt workshop slides.

**Comment by pmcharrison** [comment]
Hi @jessesnyder, thanks for talking it through. You're absolutely right about us not wanting to mandate an existing HIT and assignment, so that makes sense that we'd automate sending them an email when the HIT is ready, like you say. 

Good that you found the info about HIT creation on the workshop slides. One small thing has changed since then - we no longer require them to write detailed feedback on the compensation HIT, because we've already got that from our prior discussions with the Turker. So, the HIT is as minimal as possible at this point.

**Comment by jessesnyder** [comment]
I had a fair amount of work to do to increase the flexibility of Dallinger's `MTurkService` class to be able to create different types of HITs without a lot of additional hacky code, but now that that's done I think the actual feature will be [easy](https://twitter.com/kentbeck/status/250733358307500032).

I added a method to the MTurkRecruiter to do the actual work, for lack of a better place at the moment. Here's the completely untested sketch:
```
    def compensate_worker(self, worker_id, dollars, notify=True):
        """Pay a worker by means of a special HIT that only they can see.
        """
        qualification = self.mturkservice.create_qualification_type(
            name="Dallinger Compensation Qualification",
            description=(
                "You have received a qualification to allow you to complete a "
                "compensation HIT from Dallinger for ${}.".format(dollars)
            )
        )
        qid = qualification["id"]
        self.mturkservice.assign_qualification(
            qualification_id=qid, worker_id=worker_id, score=1, notify=notify
        )
        hit_request = {
            "experiment_id": "(compensation only)",
            "max_assignments": 1,
            "title": "Dallinger Compensation HIT",
            "description": "For compenation only; no task required.",
            "keywords": [],
            "reward": float(dollars),
            "duration_hours": 1,
            "lifetime_days": 3,
            "question": MTurkQuestions.compensation(sandbox=self.mturkservice.is_sandbox),
            "qualifications": [MTurkQualificationRequirements.must_have(qid)],
        }
        hit_info = self.mturkservice.create_hit(**hit_request)

        return {
            "hit": hit_info,
            "url": self._mturk_hit_url(hit_info["type_id"])
        }
```

Once I put the pieces together I saw that we optionally notify a worker when we assign them a qualification. If the name and description are visible to them (ideally in the email they receive), then that may be a good enough notification, and would not require you to obtain their email address at all.

Let me know if this looks like what you had in mind.

## Other Artifacts of Success

![Screen Shot 2020-04-02 at 6 16 10 PM](https://user-images.githubusercontent.com/63560/78314279-525c6400-750e-11ea-8f4f-d8721dd8ba2b.png)

![Screen Shot 2020-04-02 at 6 17 29 PM](https://user-images.githubusercontent.com/63560/78314285-58524500-750e-11ea-946a-8a055093a772.png)

**Comment by pmcharrison** [comment]
Great! This looks perfect.

**Comment by jessesnyder** [comment]
This is looking promising:
```
$ dallinger credit_turker --worker_id A2ZTO3X61UKR1G --dollars 2 --sandbox --notify
2020-04-03 11:46:34,817 - /Users/jesses/py_dev/Dallinger3/dallinger/recruiters.py - INFO - Initializing MTurkRecruiter...
----------------------  ---------------------------------------
id                      3FO95NVK5CTJJYRBZPVMMH2V708SRC
type_id                 3LC6UUY7PR436QX7EQBT78SIEH3DDQ
created                 2020-04-03 11:46:36-07:00
expiration              2020-04-06 11:46:36-07:00
max_assignments         1
title                   Dallinger Compensation HIT
description             For compenation only; no task required.
keywords                []
qualification_type_ids  ['3TFHWR10DX3JD0NZFGS3SCGZT7JE3C']
reward                  2.0
review_status           NotReviewed
status                  Assignable
annotation
----------------------  ---------------------------------------
```
## Email received
![Screen Shot 2020-04-03 at 11 46 59 AM](https://user-images.githubusercontent.com/63560/78394765-19210400-75a1-11ea-97e2-edaa5a4a4f33.png)

## HIT available
![Screen Shot 2020-04-03 at 11 50 38 AM](https://user-images.githubusercontent.com/63560/78394961-6a30f800-75a1-11ea-93b4-90aeda0c47bb.png)

## Compensation confirmed
![Screen Shot 2020-04-03 at 11 49 42 AM](https://user-images.githubusercontent.com/63560/78394972-72893300-75a1-11ea-86a9-1c6a66c77029.png)

It would be nice if HIT creation included the *name* of the required Qualification instead of just the ID, so you could easily refer to the same identifier if you need to correspond with the worker, but alas, it does not.

**Comment by raja-marjieh** [comment]
Hi everyone, thanks a lot for the automatic compensation functionality, it's really great! I'd like however to bring to your attention two issues that we've noticed:
1. The command seems to only accept integer compensation values

<img width="841" alt="Screenshot 2020-04-20 at 18 14 25" src="https://user-images.githubusercontent.com/64031078/79776391-f8450680-8335-11ea-885c-125ab26693b9.png">

2. In the automatic notification email, the actual name of the compensation HIT is not mentioned, i.e. "Dallinger Compensation HIT", nor the amount of money that the worker should receive.

**Comment by raja-marjieh** [comment]
Also, 
3. upon accepting the compensation HIT, no confirmation email of the payment was received, however it's not something that I was able to test properly yet. 

Thanks again!

**Comment by jessesnyder** [comment]
@raja-marjieh Thanks for testing it out; I appreciate it!

1. I can change the command to accept decimal values if that's valuable. I went with the simplicity of ints because it takes rounding out of the equation and I didn't think it was likely that you'd compensate someone a fraction of a dollar, but it's not hard to change.

2. The email messages come directly from MTurk, and they announce the assignment of the _qualification_ rather than the HIT itself. There's technically no way to assign a HIT directly and notify a worker, so I did my best to make the connection as obvious as possible. Do you think it would help if the qualification and the HIT had exactly the same title (and possibly a more eye-catching/obvious title)?

3. I only tested in the sandbox, and I don't think I ever receive payment notification via email when working there. We're leaning on standard MTurk behavior here, so the notifications will be whatever generally happens when you submit a HIT that's configured to compensate you automatically with zero delay.

**Comment by jacobyn** [comment]
Hi Jesse,
Thank you for this. Is there any way to make a custom massage within getting the qualification? Because there is no way the turker will know to try to search for the HIT. Another option is an automatic massage sent by us via email (in this case we will need to specify also the email address, typically we know it)

**Comment by jessesnyder** [comment]
For the qualification, we get to specify the title and the description. Here's what I'm doing currently:
```
        qualification = self.mturkservice.create_qualification_type(
            name="Dallinger Compensation Qualification - {}".format(
                generate_random_id()
            ),
            description=(
                "You have received a qualification to allow you to complete a "
                "compensation HIT from Dallinger for ${}.".format(dollars)
            ),
        )
```

Frustratingly, the description is not included in the email sent to the worker; only the name/title is.
It would be easy to allow specifying the title as an argument to the `dallinger compensate` command, but maybe that's not going to be enough anyway.

If you know the email address then we can attempt to send an email directly from Dallinger, assuming all the email configuration is set up correctly, which can itself be a challenge (see my lengthy document at http://docs.dallinger.io/en/latest/email_setup.html). We'd probably need to first check for valid email setup, and only proceed with creating the qualification and HIT if things look like they're going to work on the email side. It definitely adds some complexity and fragility.

**Comment by pmcharrison** [comment]
Hi @jessesnyder: @jacobyn, @raja-marjieh and I had a chat yesterday about these email questions. We would like to prioritise getting this compensation service into the next release of Dallinger (hopefully in the next few days), even without the email service - what you currently have implemented will still save us a lot of time, and we'd like to roll it out ASAP. Adding email to this command can then be a subsequent issue that we complete later, probably in the next sprint. I will add an issue now with a few additional thoughts about the email service.

**Comment by jessesnyder** [comment]
@jacobyn @raja-marjieh @pmcharrison 
I got down to business on this and it's very close. Let me know what you think. I'm happy to do a Slack call, since sometimes that's just way easier. There are now two commands, explained below:

1. `dallinger compensate`
2. `dallinger email_test`

## Updated compensate command


### Demo
```
$ dallinger compensate --worker_id A...........G --email jesse@example.com --dollars 2.50 --sandbox
2020-04-21 16:16:01,320 - /Users/jesses/py_dev/Dallinger3/dallinger/recruiters.py - INFO - Initializing MTurkRecruiter...


You are about to pay worker "A...........G" $2.50 in "sandbox" mode using the "mturk" recruiter.
The worker will be notified by email. Continue? [y/N]: y

❯❯ HIT Details
----------------------  -----------------------------------------------------------------------------
id                      3OPLMF3EU5GB0N4TM9H41BJQFISNL5
type_id                 3H2ZGQZOTY1K27XF1MZJE05BCNUYXU
created                 2020-04-21 16:16:04-07:00
expiration              2020-04-24 16:16:04-07:00
max_assignments         1
title                   Dallinger Compensation HIT
description             For compenation only; no task required.
keywords                []
qualification_type_ids  ['3BR5SIVR7WNK7CZNAVZNB658XCQGEO']
reward                  2.5
review_status           NotReviewed
status                  Assignable
annotation
worker_url              https://workersandbox.mturk.com/projects/3H2ZGQZOTY1K27XF1MZJE05BCNUYXU/tasks
----------------------  -----------------------------------------------------------------------------

❯❯ Qualification Details
-----------  ------------------------------------------------------------------------------------------------------
id           3BR5SIVR7WNK7CZNAVZNB658XCQGEO
created      2020-04-21 16:16:03-07:00
name         Dallinger Compensation Qualification - T6AAE5
description  You have received a qualification to allow you to complete a compensation HIT from Dallinger for $2.5.
status       Active
-----------  ------------------------------------------------------------------------------------------------------

❯❯ Worker Notification
----------  ----------------------------------------------------------------------------------
subject     Dallinger Compensation HIT
sender      admin@example.com
recipients  ['worker@example.com]
body        A special compenstation HIT is available for you to complete.
            Title: Dallinger Compensation HIT
            Reward: $2.50
            URL: https://workersandbox.mturk.com/projects/3H2ZGQZOTY1K27XF1MZJE05BCNUYXU/tasks
----------  ----------------------------------------------------------------------------------
```
## Email validation
My idea for email config checking was separate from the function of compensation, since this is a general state of the experimenter's setup. I added a `dallinger email_test` command, that does two things:

1. It checks to make sure you have all the required config keys set up (it doesn't do much to validate them as email addresses, etc. but this would be easy to add)
2. It sends an email using the configuration, from `dallinger_email_address` to `contact_email_on_error`. If this is working and you receive the email, you can basically have confidence in your configuration generally

You may still have the problem of getting the worker's email wrong, but if that happens, dealing with it with tooling seems like wrong approach.

### Demo

#### Sad Path
```
$ dallinger email_test

❯❯ Email Config
-----------------------  --------------------------
smtp_host                smtp.gmail.com:587
smtp_username            jesse@rasikaconsulting.com
contact_email_on_error   jesse@rasikaconsulting.com
smtp_password            ???
dallinger_email_address  jesse@rasikaconsulting.com
-----------------------  --------------------------

❯❯ There are mail configuration problems. Fix these first:
Missing or invalid config values: smtp_password
```

#### Happy Path
```
$ dallinger email_test

❯❯ Email Config
-----------------------  --------------------------
smtp_host                smtp.gmail.com:587
smtp_username            jesse@rasikaconsulting.com
contact_email_on_error   jsnyder@wesleyan.edu
smtp_password            fug......v
dallinger_email_address  jesse@rasikaconsulting.com
-----------------------  --------------------------

❯❯ ✓ email config looks good!

❯❯ Sending a test email from jesse@rasikaconsulting.com to jsnyder@wesleyan.edu

❯❯ ✓ Test email sent successfully to jsnyder@wesleyan.edu!
```

All that remains is that I need to change the way I'm constructing email messages. It turns out the way I'm doing it now doesn't work on Python 2.

**Comment by raja-marjieh** [comment]
Hi @jessesnyder, we just tested the new commands and they seem to work perfectly! Thanks a lot! we really appreciate it!
