### ISSUE TITLE
Automated testing -- 5 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2029]
As a requester, we would like to understand how best to construct automated tests for Dallinger experiments. We are not aware of any documentation on this problem, though we understand that the developers do use a suite of automated tests. In particular, we’re interested in how the ‘dallinger deploy’ command may be wrapped within a test, and how we can programmatically interact with the resulting experiment (e.g. using a headless browser, or by interacting directly with the experiment object).

**Comment by skleinfeldt** [comment]
Need to discuss with Nori

**Comment by pmcharrison** [comment]
Here's an example of a simple automated testing framework I put together for psychTestR: https://pmcharrison.github.io/psychTestR/articles/d-automated-testing.html

**Comment by MatthewWilkes** [comment]
So, I was looking at this briefly in the previous iteration. There are a few ways to start the server, but there are gotchas. First up, we can't use the existing Deployment machinery because we need that to run in a thread (to not block the tests from running) but the heroku runner assumes it always runs in the main thread so that fails.

Secondly, we can't simply start up the server reliably without duplicating all the work the deployment process does.

I think the best approach for this is to create a fixture that uses subprocess to set this up through dallinger debug, with appropriate code to get and set the starting working directory after it finishes. We can have a pytest fixture that effectively runs the debug server and returns a URL to it, and another one to return a selenium testbrowser object, similar to how bots set them up.

**Comment by alecpm** [comment]
@pmcharrison @jacobyn I think this is ready for some testing and feedback. The branch is `issues/2029-experiment-testing` (PR #2106). There's an example test in `demos/tests/test_bartlett.py`. There are still some mysterious issues with running test coverage checks under tox/travis that we've been trying to get to the bottom of, but those should not affect your testing.

**Comment by pmcharrison** [comment]
Hi @alecpm, this looks really cool! Thank you.

Unfortunately I'm struggling to get the main tests to run, though. I can call this:

```
pytest --verbose --runslow demos/tests/test_bartlett.py
```

and I get this:

```
demos/tests/test_bartlett.py::TestBartlett1932::test_bartlett_selenium[bot_recruits0] SKIPPED  
```

`test_bartlett_selenium` gets skipped because of the `bot_recruits` fixture. I thought that perhaps it's detecting a lack of Selenium installation, and silently skipping the test. However, this seems not be the case, my Selenium works fine. Can you advise? The current documentation (http://docs.dallinger.io/en/latest/running_the_tests.html) doesn't seem to help with these issues.

**Comment by alecpm** [comment]
@pmcharrison You tested it right before some updates to the text I intended to make to clarify this very issue. You'll need to add a couple of parameters to get that test to run. First is `--runslow` because the test is explicitly marked as slow (all tests that launch an experiment are slow, and this one does a full run through so it's extra slow). The second is a flag to tell pytest which selenium driver(s) you want to use. You can use `--phantomjs`, `--chrome`, `--firefox` or any combination of those (the test will be run once for each driver you choose).

**Comment by pmcharrison** [comment]
Ah - thanks for the quick response, @alecpm ! It worked great, though I had to make a minor edit to make the test run successfully on my machine. In particular:

``` js
bot.driver.get("javascript:window.localStorage.clear();")
```

failed, because the command returned a response of unexpected format. But here we're only interested in the side effect of the call, so we can replace it with the following:

``` js
bot.driver.execute_script("javascript:window.localStorage.clear();")
```

and then it works well for me.

@jessesnyder said that he could give me permissions to push the changes to this branch.

Also, there are a few deprecation warnings that I'll fix while I'm at it, like this:

``` py
DeprecationWarning: use driver.switch_to.window instead
  self.driver.switch_to_window(self.driver.window_handles[-1])
```

**Comment by pmcharrison** [comment]
It is very satisfying (but spooky!) to see the experiment completing itself!

**Comment by alecpm** [comment]
Interesting, I initially used `bot.driver.execute_script("window.localStorage.clear();")` but it errored for me on PhantomJS 2.1.1, so I switched to the current spelling of that command. What driver and driver version are you using? Unfortunately getting the browser and driver versions sync'd up is always a bit of a pain with selenium and friends.

**Comment by pmcharrison** [comment]
Oh no! I'm using ChromeDriver 80.0.3987.106 (downloaded this afternoon). Any use?

**Comment by alecpm** [comment]
Does your change work for you with PhantomJS, if it's installed? PhantomJS is probably the only driver that actually needs that call because it retains local storage across sessions. It may even be possible to remove that call now because I added a different way to ensure PhantomJS creates a new local storage. I'll double check.

**Comment by pmcharrison** [comment]
Yes, works with the latest version of PhantomJS. Incidentally, I get deprecation warnings for PhantomJS, do you?

```
UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
```

**Comment by jessesnyder** [comment]
> ```
> UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
> ```
That's the deprecation I noticed either locally or on Travis over the past few days.

**Comment by jessesnyder** [comment]
@pmcharrison I don't have permission to give you permission 🙂 but I've appealed to Jordan Suchow to do so.

**Comment by alecpm** [comment]
I saw those too, though it seems a little odd since what's the point of PhantomJS if you can't use it with selenium. Not sure I want to get into setting up headless Chrome on Travis until we really need to.

I've removed those `localStorage` clear calls completely since they are effectively for PhantomJS only and we have a better solution for that now.

**Comment by MatthewWilkes** [comment]
That PhantomJS depreciation has been present for a very long time. I think the only reason we didn't drop support for it earlier was for trying to get large numbers of bots running. Even headless chrome uses a lot of resources.

**Comment by pmcharrison** [comment]
Interesting, good to know!
