### ISSUE TITLE
Logging Flask routes -- 2 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2030]
Currently calls to Flask routes are logged with entries like the following:

11:32:42 web.1      |  INFO:geventwebsocket.handler:127.0.0.1 - - [2020-03-05 11:32:42] "GET /timeline/1/SJ0VYZ?participant_id=1 HTTP/1.1" 200 5983 0.015252

It would be useful to know what the final two numbers refer to (here they are “5983” and “0.015252”.

It would be useful if these logs contained the following (additional) information:

- The time taken to process the request.
- The URL arguments (i.e. the bits denoted using “<>” in the Flask route).
- The URL parameters (i.e. the bit following “?” in the URL).
- Any JSON or other message data that accompanies the request. It should be possible to provide a data formatting function for this (so that, for example, an uploaded audio file can simply be represented as a sample rate and duration).

Here is a nice example that I found online: [https://dev.to/rhymes/logging-flask-requests-with-colors-and-structure--7g1](https://dev.to/rhymes/logging-flask-requests-with-colors-and-structure--7g1)

**Comment by jessesnyder** [comment]
Nothing is ever that straightforward. I had quite a time figuring out where the current logging is coming from, and on what basis it's formatted. It turns out it's a combination of `gevent.pywsgi.WSGIHandler` and `geventwebsocket.hander.WebSocketHandler`, where the format is hard-coded in the former. I attempted to find a seam in the whole process to disable this logging, but was unsuccessful so far. We may just need to live with two logging statements for each request, unless @MatthewWilkes can bail me out here.

**Comment by pmcharrison** [comment]
Ah strange! So you can’t override the Flask log formatter as described here? https://flask.palletsprojects.com/en/1.1.x/logging/

**Comment by MatthewWilkes** [comment]
@pmcharrison I'm afraid it's not quite that simple. That lets you change the logging format, which is everything that accompanies the message.

The above example breaks down like this:

| Time | Processes | Level | Logger name | Message |
| --- | --- | --- | --- | --- |
| 11:32:42 | web.1 | INFO: | geventwebsocket.handler: | 127.0.0.1 - - [2020-03-05 11:32:42] "GET /timeline/1/SJ0VYZ?participant_id=1 HTTP/1.1" 200 5983 0.015252 | 

So, almost all of the substantive information is a string passed to message. Changing the formatter would let us add or remove extra info either side of that, but only the message section has access to the request and that is hard-coded.

**Comment by MatthewWilkes** [comment]
@jessesnyder I agree, there's no easy way of doing this. I think we could disable this logigng relatively easily, by putting a filter on that logger, and we could probably insert a logger closer to the application level (as in the think from the original question), but I don't think that would be foolproof. 

To answer the questions in the original question: the two numbers at the end are the number of bytes in the response and the time taken to generate the response. 

I'd be inclined to suggest that you do custom logging for the things you need, rather than trying to build a framework for it into dallinger. Almost all of your requirements can be achieved through processing the existing logs, which are in the apachelog format, but things like the JSON logging could definitely be done in application-level.

@jessesnyder Maybe a gist or a bit of documentation to do a dallinger equivalent of the linked info?

**Comment by pmcharrison** [comment]
Thanks both! I think I agree with @MatthewWilkes here - on the basis of what you've said, it seems wise not to build a new logging framework in Dallinger.

Can I suggest the following, instead? Please could you create some documentation/examples for how custom logging should work in Dallinger experiments? In particular, supposing that the implementation is spread over separate files (e.g. `models.py` and `experiment.py`), and supposing that you want to log at different levels (warn, debug, info)? So far I've only had success with the info level. If you can think of any clever examples with decorators, that would be great. For example, I can imagine something like this being useful:

``` python
@extra_routes.route("/upload_questionnaire/<int:participant_id>", methods=["POST"])
@log_json
def upload_questionnaire(participant_id):
    ...
```
where `log_json` causes the logger to log the uploaded JSON.

**Comment by jacobyn** [comment]
I am sure I understood it, but perhaps we can have two kinds of logs? We are usually using papertrail for following the logging. In the near future we would like to use dashboard. In both cases if the new logger would just add a string to mark that this segment is part of the "formatted log" something like "<FORMAT-LOG>" we then can search this string and don't care if other logs are ALSO printed. The point is that the non-formated log would be still there, but we will have a better control  for the rest. Would  that work? (If  I understood correctly this will prevent the need to disable the current log)

**Comment by pmcharrison** [comment]
Nori and I discussed, we are happy just with the documentation solution, no code needs to be written here.
