### ISSUE TITLE
Honor .gitignore exclusions when building experiment temp directory for Heroku deployment -- 3 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2031]
As a developer, we should be able to provide a .dallingerignore file, functioning similar to .gitignore, that instructs Dallinger not to upload particular files or folders during deployment.

**Comment by pmcharrison** [comment]
Since we made this request, we realised that .gitignore already performs this functionality, can you confirm? Is this documented? A related problem is that `dallinger --verify` doesn't seem to account for these ignored files, and ends up overestimating the directory size.

**Comment by jessesnyder** [comment]
That sounds vaguely familiar. If so, and the problem is with `--verify`, I think it makes sense to rename the ticket and work on that problem instead. My sense is that the ticket size is similar anyway. Would that be equally valuable @pmcharrison?

**Comment by pmcharrison** [comment]
Sounds good. Thanks very much!

**Comment by jessesnyder** [comment]
I thought I was just a bit dense with replicating Git's complete .gitignore file matching behavior, but I think it may actually be this complicated:

https://github.com/mherrmann/gitignore_parser/blob/master/gitignore_parser.py

We could just depend on this pypi release, except that it doesn't support Python < 3.5:
https://pypi.org/project/gitignore-parser/

The other options: 
1. Copy all the code from that package with only partial comprehension of what it does
2. Do some kind of trick with Git to find the files that will be copied
3. match .gitignore behavior imperfectly, which might get us 95% of the way there if people aren't typically using elaborate globbing patterns (the test case I was trying and failing to support was `**/subdir/*`)

I don't like 1 or 2.

@MatthewWilkes I'd appreciate your thoughts here.

**Comment by pmcharrison** [comment]
On this point, I reckon it's worth thinking about the motivation for the `dallinger --verify` check, and why it prohibits large repository sizes. I would guess that this is motivated by upload time, right? Large repositories are slow to upload. 

When Heroku deploys using git, it doesn't just upload the local directory, but it uploads the repository history - in other words, it uploads the whole .git folder. So, a simple substitute here (avoiding messy parsing) would be just to check the size of the .git folder. What do you think?

**Comment by jessesnyder** [comment]
@pmcharrison The size check actually grew out of a specific problem where a researcher nearly filled their hard drive running `dallinger debug` with large video files in their experiment directory. With each run, a new temp directory was generated, and any files not excluded by the existing pattern matching were copied there. As I recall they were also pushed to Heroku on deployments, but that was a secondary problem(!)

To summarize exactly how things work now:

* The temp directory creation process uses a set of file name patterns to exclude certain files from being copied from your experiment working directory, but it makes no assumptions about whether your working directory is a git repository. (Among the exclusions is the `.git` directory, so if your experiment _is_ a git repo, we don't copy its "git-ness".)
* If you're deploying to Heroku, once the temp directory is populated with a subset of your files and files copied from dallinger, the resulting files are added to a _new_ repository (`git init; git add --all`) and pushed to the Heroku remote
* When you run `dallinger debug/sandbox/deploy`, the size check uses the same exclusion patterns as the temp directory copy mechanism, to preemptively determine if the files that would be copied to the temp directory exceed the max

So, the current check really focuses on avoiding a large copy to the temp directory. However, if you _do_ include a `.gitignore` file, nothing excluded by that file will ever be deployible (though it would be accessible in a `debug` run), so it's reasonable to exclude it from the temp directory copy as well.

An idea that doesn't seem too crazy:  what if we checked to see if you have a .gitignore file in your experiment directory, and if so, we used `git ls-files` to determine the files to copy to the temp directory, instead of the current system (copy everything unless it's excluded). The same list could be used in the size check. This is easy enough to explain, with (I think) predictable results.

**Comment by pmcharrison** [comment]
Thanks Jesse!

 

> An idea that doesn't seem too crazy: what if we checked to see if you have a .gitignore file in your experiment directory, and if so, we used git ls-files to determine the files to copy to the temp directory, instead of the current system (copy everything unless it's excluded). The same list could be used in the size check. This is easy enough to explain, with (I think) predictable results.

 

Sounds good to me! This would help resolve inconsistencies between `dallinger debug` and `dallinger deploy`.
