### ISSUE TITLE
Changing config to allow for different server sizes for workers and web servers -- 2 points

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2088]
Currently the worker servers and the web servers are constrained to be the same size (e.g. “performance-M”, which is not ideal. We would like to be able to specify different sizes for the web and worker dynos in the config.txt.

**Comment by alecpm** [comment]
I'm thinking of adding an optional `dyno_type_worker` config parameter to retain backwards compatibility. If only `dyno_type` is set, then that type would be used for both web and worker dynos, as it is now. If `dyno_type_worker` is set it would override the dyno type for worker dynos, leaving the `dyno_type` for the web dynos only. Does that seem like a reasonable and relatively straightforward approach?

**Comment by pmcharrison** [comment]
Hi @alecpm, good idea to retain backwards compatibility. To me, the most intuitive approach would be a slight variant on yours: have `dyno_type` determine the default dyno type, which can be optionally overridden by the more specific arguments `dyno_type_worker` and `dyno_type_web`. (Otherwise the asymmetry between web and worker is arguably a bit unintuitive)
