### ISSUE TITLE
Manage MTurk HITs, part II: ?pts

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#2226]
[This continues #2116 and #2200 0] also Based on https://manage-hits-individually.s3.amazonaws.com/v4.0/index.html#/credentials

- [x] HIT ad page as an iframe (see here: https://docs.google.com/presentation/d/1BozvqVDHqtltIXGVspjHaD4EdTaXrNC4dXbtr4GdQsE/edit?usp=sharing)
- [x] The ability to expire the HIT
- [x] The ability to extend the HIT
    - [x] Extend until (select a date from a calendar) (see here https://docs.google.com/presentation/d/1BozvqVDHqtltIXGVspjHaD4EdTaXrNC4dXbtr4GdQsE/edit?usp=sharing)
    - [x] Extend by (number of HITs)
- [x] Simple link to the requester account in MTurk (simple link to https://requester.mturk.com/)
- [x] Simple link to the qualification page in MTurk (simple link to https://requester.mturk.com/qualification_types)

**Comment by jessesnyder** [comment]
@jacobyn I think we decided that this approach was OK for HIT expiration? (Clicking "Expire HIT" opens a small popup with the correct `dallinger expire` command ready to go. Behind the scenes this calls `UpdateExpirationForHIT()` with an instruction to expire it immediately. See https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_UpdateExpirationForHITOperation.html

![Screen Shot 2020-07-02 at 2 39 30 PM](https://user-images.githubusercontent.com/63560/86411569-fbcc0680-bc71-11ea-9420-d95c7233e9d5.png)

**Comment by jessesnyder** [comment]
@MatthewWilkes We should probably coordinate an approach for these CLI command helpers. If you want to copy what I did here, it's in `features/dashboard-2226-mturk-hits`.

**Comment by pmcharrison** [comment]
Hi @jessesnyder , looks cool! Just to be clear, when you say

>  Behind the scenes this calls UpdateExpirationForHIT()

you mean behind the scenes of the CLI command, not behind the scenes of the button press?

**Comment by jessesnyder** [comment]
@pmcharrison That's right. `dallinger expire` calls our `MTurkService` class which calls UpdateExpirationForHIT() (with boto3 in the middle there, but we can ignore that!).

**Comment by jessesnyder** [comment]
Here's a short screencast to elicit some early feedback. Looking for suggestions on what Extend HIT should do (or, perhaps more specifically, how simple an implementation would be acceptable ;-) )
https://www.screencast.com/t/I5KqSeveWYzg

**Comment by pmcharrison** [comment]
Cool, thanks for sharing! Looking good so far.

Regarding Extend HIT, the functionality you have proposed (choose date, choose number of additional assignments) looks ideal.

Regarding how to implement Extend HIT, to me, it makes sense to be consistent with the implementation of Expire HIT, where the implementation goes via a CLI command. It makes sense to do the same here, in part because it seems to be a speedier solution to implement, and in part because it could be useful to provide this functionality to people who are just using the CLI, not the dashboard.

Regarding the UI, I guess a nice thing to add would be a copy to clipboard button. There is also a bit of ambiguity to the UI, it's not clear to the user whether clicking the button is actually going to expire the HIT, or just display a CLI command. I quite like the way that GitHub deals with this:

<img width="1114" alt="Screenshot 2020-07-03 at 09 53 10" src="https://user-images.githubusercontent.com/22684998/86451571-02f72100-bd13-11ea-8e8e-b0fdb18e7b61.png">

But of course there are implications for screen real-estate. Whatever happens, though, I do think it's pretty useful to have the 'copy-to-clipboard' button. And as you note, this problem comes up in other places, so maybe it's a good idea to invest a little time in a nice solution that then can be used everywhere.
