### ISSUE TITLE
Adding a fail_reason column: 3pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2254]
We propose that the fail() method should have an additional optional argument, “reason”, which is a string describing the reason why the object was failed. This should be stored in a new column called “fail_reason” in the database. For back-compatibility, this can have a default value, e.g. "default".

**Comment by thomasmorgan** [comment]
I think this sounds reasonable. Just think carefully about the relationship between this column and the status column in the ppt table - status already tries to give information about why a participant might have been failed (e.g., bad_data) so there is some overlap here.

**Comment by pmcharrison** [comment]
Thanks, good point. Seems like there might indeed be some duplication with this field, not sure how solve that while maintaining consistency for the other failable object types.

**Comment by jessesnyder** [comment]
@pmcharrison Some objects propagate failure to related objects in their `fail()` method. Do you have a clear sense of what you'd like to do in these cases? My first thought would be to provide a reason message when failing the related objects, and then append to this message if a reason message was provided in the "top level" call to `fail()`.

For example, `Node.fail()` could be modified like this:

```python
    def fail(self, reason=None):
        """
        Fail a node, setting its status to "failed".
        ...

        """
        if self.failed is True:
            raise AttributeError("Cannot fail {} - it has already failed.".format(self))
        else:
            self.failed = True
            self.time_of_death = timenow()
            self.network.calculate_full()
            explicit_failure_reason = ": {}".format(reason) if reason is not None else ""
            source_failure_reason = "Cascading fail() initiated from {}{}".format(self, explicit_failure_reason)

            for v in self.vectors():
                v.fail(reason=source_failure_reason)
            for i in self.infos():
                i.fail(reason=source_failure_reason)
            for t in self.transmissions(direction="all"):
                t.fail(reason=source_failure_reason)
            for t in self.transformations():
                t.fail(reason=source_failure_reason)
```

**Comment by jessesnyder** [comment]
Not directly related, but I'm curious how this API (which is consistent across all the various `fail()` methods) is working in practice:

```python
        if self.failed is True:
            raise AttributeError("Cannot fail {} - it has already failed.".format(self))
```
Is it helpful to have an exception raised, or would it be better if this were quietly idempotent? The current implementation seems like a recipe for a lot of boilerplate try/catch/(pass)

**Comment by pmcharrison** [comment]
Thanks for the interesting points, @jessesnyder !

Regarding cascading fails, your solution seems good, though in long cascades (which are common) the error messages would get very long, and if one wanted to decode the failure chain it would feel pretty hacky (regex etc). 

How about biting the bullet and adding another column, `failure_parent`? This could be a little JSON that uniquely identifies the parent (presumably by providing both the class name and the ID).

Regarding the second point about the exception that's raised if you try and fail twice: yes, I find that functionality pretty awkward actually! I disable it whenever I subclass these objects. So, I wouldn't complain if you made it quietly idempotent :-)

**Comment by thomasmorgan** [comment]
@jessesnyder and @pmcharrison 

I'm surprised you are running in to this error with failure cascades, my expectation is that it should be hard to cause the error to arise because the cascades specifically exclude already failed items from the cascade. For instance:

```
            for v in self.vectors():
                v.fail(reason=source_failure_reason)
```

returns a list containing only non-failed vectors.

Also, FWIW, I think having a `failure_parent` in addition to `failure_reason` is a good idea if you are interested in tracking cascades as well as understanding their root cause.

**Comment by pmcharrison** [comment]
Yes, I guess most built-in Dallinger queries exclude failed objects by default. My cases must have used queries without that exclusion criterion. You're right that you can avoid this problem if you use queries excluding failed objects.

**Comment by thomasmorgan** [comment]
Ah OK, so the issues weren't with the cascade itself, rather you were doing your own queries, including failed objects, and trying to fail them directly. Yes, this will cause problems. Still, I'd be inclined to keep the error raising in place just to force users to think about exactly what their code is doing. But I guess I'm cruel like that!

**Comment by pmcharrison** [comment]
I guess writing software frameworks is all about 'the principle of least surprise' - a good Dallinger function should strive not to surprise the user. So, then our job is to work out what the user expects. When I came to Dallinger, I expected that `fail` should be idempotent, but you, with more Dallinger experience, expects that it shouldn't be idempotent. In this case, I defer to your seniority ;-)

**Comment by thomasmorgan** [comment]
That's a good principle, and I'm not sure what it would suggest in this case.

I also think about these errors as being like a linter. They flag to the user when they are doing something bad/risky/etc. Whether you feel an error or a warning better serves this purpose is debatable, but my gut feeling is that most users won't bother to understand warnings in the logs if their experiment still "works" and so errors are a good way to force their hand. But maybe this is overly paternalistic and infantilizes the user. I don't know. I kinda like enforcing "good" practices though!

@jessesnyder thoughts?

**Comment by jessesnyder** [comment]
I'm regretting asking about `fail()` idempotence-vs-not, because now I'm having trouble tracking which issue is being discussed. :-) 

### Cascade
On the cascade question, if the fail() cascade will never (rarely?) be more than 2 levels deep (parents, but no grandparents) `failure_parent` seems like overkill, but maybe you envision doing some analysis where a separate value would be helpful(?) I'm wondering if we just lean down the content of my initial proposal and still retain all the information?

```python
node1.fail("boom!")
```

On this node, the `fail_reason` would be "boom!".

On child/related Vectors, it could be "Node 1->boom!"

On grandchildren (Transmissions, say), it would then be "Vector 1->Node 1->boom!"

### Idempotence

In general, things become a lot simpler when you don't need to track state, or check it, and can just declare what you want the state to be. So, in the absence of any other information, I'd opt for idempotence. On the other hand, I sympathize with @thomasmorgan's argument: it could introduce the temptation to apply lots of redundant `fail()` calls without coming to grips with the fact that you don't understand how your experiment works (I'm reminded of `session.commit()`, where there's a tendency to "just try adding a couple to see if they fix it"). I'd say a tie goes to the status quo, and we make no change?

**Comment by pmcharrison** [comment]
Sounds good to me, @jessesnyder ! Seeing your example, parsing the `fail_reason` wouldn't be a nightmare if you really had to do it, and I like the simplicity. Let's just make sure that something graceful happens if somehow the chain gets really long? (e.g. not exceeding the SQL column limit) I'm sure you would do that anyway :-)

**Comment by thomasmorgan** [comment]
@jessesnyder thanks for the detailed write up.

**Cascades**
Yes, there should only ever be parents, and never grandparents. This is because failing a node triggers the failing of all its infos, transmissions, vectors, etc, but (1) not any other nodes, and (2) only nodes being failed triggers further failures. As such, the cascade should only ever be from a node to its associated objects. This means that if a user wants to fail multiple nodes they will need to initiate multiple cascades. The suggestion for concatenating the cascading node id to the failure reason for dependent object is good.

The only exception I can think of is entire networks being failed. Does Dallinger allow this? If so, it probably fails all nodes within the network, at which point the network will be a grandparent in the cascade, but I think that is the longest possible cascade.

**Idempotence**
Ha, yeah. Before we hired you guys, and before we figured out the largely automatic adding of objects to the db upon creation our code was overflowing with `session.commit()`. This is exactly the sort of thing I want to avoid. But, I agree there are reasons for doing it both ways (and indeed `node.connect` raises a warning if a connection exists, not an error, so Dallinger isn't even internally consistent), but yes, lets stick with the status quo for now.

**Comment by pmcharrison** [comment]
> Yes, there should only ever be parents, and never grandparents. This is because failing a node triggers the failing of all its infos, transmissions, vectors, etc, but (1) not any other nodes, and (2) only nodes being failed triggers further failures. 

I think it just depends how you construct your experiment? In our chain-based experiments, if you fail a node halfway along a chain, it will fail all the descendant nodes. So, you could have 100 generations easily.

**Comment by thomasmorgan** [comment]
Yes, but this is custom experiment behavior, right? The default is for nodes to fail other objects but not other nodes?

Also, I took a quick look at the code and networks can be failed and will fail nodes, so this will produce grandparents. The same is true of participants too, they fail nodes and so on.

**Comment by pmcharrison** [comment]
> Yes, but this is custom experiment behavior, right? The default is for nodes to fail other objects but not other nodes?

Yes - but I think it's reasonable custom behavior, and hence I wouldn't like to pronounce that "there should only ever be parents, and never grandparents." I think it's totally reasonable to write the code to protect the code against many-generation failing.

**Comment by jessesnyder** [comment]
I'm still contemplating the format of the failed_reason message, but I can definitely confirm that we already get multiple "levels" just through wiring up objects in what I assume is a fairly typical way. I'd like to use a format that would prevent any ambiguity about whether there was an explicit reason passed at the top of the chain. I think this format will work, since if the reason ends in `->`, you know there was no explicit reason, otherwise there was (assuming you don't end your explicit reason with `->`!)

The reason messages encode "up the call stack" as right-to-left, with any explicit reason at the very end (I can't decide if this is intuitive or counter-intuitive!):

```python
    def test_network_failure_captures_cascade_in_failure_reason(self, a):
        net = a.network()
        node1 = a.node(network=net)
        node2 = a.node(network=net)
        node1.connect(whom=node2)
        info = a.info(origin=node1)
        node1.transmit(what=node1.infos()[0], to_whom=node2)
        transmission = node1.transmissions()[0]
        vector = node1.vectors()[0]

        net.fail()  # no explicit failed reason passed

        assert net.failed_reason is None
        assert node1.failed_reason == "Network1->"
        assert node2.failed_reason == "Network1->"
        assert info.failed_reason == "Node1->Network1->"
        assert vector.failed_reason == "Node1->Network1->"
        assert transmission.failed_reason == "Vector1->Node1->Network1->"

    def test_network_failure_propogates_explicit_failure_reason(self, a):
        # same setup as above

        net.fail("Boom!")  # explicit reason passed

        assert net.failed_reason == "Boom!"
        assert node1.failed_reason == "Network1->Boom!"
        assert node2.failed_reason == "Network1->Boom!"
        assert info.failed_reason == "Node1->Network1->Boom!"
        assert vector.failed_reason == "Node1->Network1->Boom!"
        assert transmission.failed_reason == "Vector1->Node1->Network1->Boom!"

```

**Comment by jessesnyder** [comment]
Maybe the arrows should point the other way?

```python
    def test_network_failure_captures_cascade_in_failure_reason(self, a):
        net = a.network()
        node1 = a.node(network=net)
        node2 = a.node(network=net)
        node1.connect(whom=node2)
        info = a.info(origin=node1)
        node1.transmit(what=node1.infos()[0], to_whom=node2)
        transmission = node1.transmissions()[0]
        vector = node1.vectors()[0]

        net.fail()  # no explicit failed reason passed

        assert net.failed_reason is None
        assert node1.failed_reason == "Network1<-"
        assert node2.failed_reason == "Network1<-"
        assert info.failed_reason == "Node1<-Network1<-"
        assert vector.failed_reason == "Node1<-Network1<-"
        assert transmission.failed_reason == "Vector1<-Node1<-Network1<-"

    def test_network_failure_propogates_explicit_failure_reason(self, a):
        # same setup as above

        net.fail("Boom!")  # explicit reason passed

        assert net.failed_reason == "Boom!"
        assert node1.failed_reason == "Network1<-Boom!"
        assert node2.failed_reason == "Network1<-Boom!"
        assert info.failed_reason == "Node1<-Network1<-Boom!"
        assert vector.failed_reason == "Node1<-Network1<-Boom!"
        assert transmission.failed_reason == "Vector1<-Node1<-Network1<-Boom!"
```

**Comment by thomasmorgan** [comment]
@jessesnyder I'd reverse the message:

"Boom!->Network1->Node1->Vector1"

It's easier to read chronological left to right

**Comment by thomasmorgan** [comment]
Also, an automatic failing can be indicated by either no message:

"->Network1->Node1->Vector1"

Or some kind of default
"Default->Network1->Node1->Vector1"
"Dallinger->Network1->Node1->Vector1"

Smiling face of doom?
" :-) ->Network1->Node1->Vector1"

**Comment by jessesnyder** [comment]
Ah, I like it. It makes sense to think of it as a chronological sequence.

**Comment by pmcharrison** [comment]
I agree with @thomasmorgan :-)

**Comment by pmcharrison** [comment]
But perhaps we could differentiate the error message from the objects? Something like:

```
Too many bananas in the network:Network1->Node1->Vector1
```

**Comment by pmcharrison** [comment]
What would be a good way of protecting the failure reason so that it's easy to extract even if it contains a colon in it?

**Comment by thomasmorgan** [comment]
I like the colon. Even if the error reason also includes colons you can still get the reason by splitting the string at the final colon instance.

**Comment by pmcharrison** [comment]
>  Even if the error reason also includes colons you can still get the reason by splitting the string at the final colon instance.

Oh yes, good point! That would be really simple.

> Ugh... I guess this assumes you don't put colons in the type of the objects. But if you do that maybe its your own fault?

Haha! I think we're safe, colons can't be in class names, can they? I just tried and had no luck, but maybe I didn't try hard enough.

> Having a different delimiter for the explicit reason makes things more complicated (I'd wanted to do that it that way initially), and I'm not sure it adds anything

I think what it adds is readability - when you have a sequence of objects separated by arrows, you assume that they're all the same, but in our case there's something special about the first one. But to be honest I don't feel strongly about it and would prefer to go with @jessesnyder 's gut, wherever that takes him :-)

**Comment by jessesnyder** [comment]
Here's my most articulate argument, using python destructuring:

```python
>>> explicit = 'Boom!->Network1->Node1->Vector1'
>>> implicit = '->Network1->Node1->Vector1'

>>> trigger, *cascade = explicit.split('->')
>>> trigger
'Boom!'
>>> cascade
['Network1', 'Node1', 'Vector1']

>>> trigger, *cascade = implicit.split('->')
>>> trigger
''
>>> cascade
['Network1', 'Node1', 'Vector1']
```

**Comment by pmcharrison** [comment]
Good enough for me :-)

**Comment by jessesnyder** [comment]
Forgot an important case, that still works without any additional checks:

```python
>>> root_only = 'Boom1!'
>>> trigger, *cascade = root_only.split('->')
>>> trigger
'Boom1!'
>>> cascade
[]
```

**Comment by thomasmorgan** [comment]
Agreed, the splitting examples are really lovely. Go for it.

**Comment by jessesnyder** [comment]
I decided it's not worth including this code, but I'll stick it here for posterity. 


```python
def parse_failed_reason(reason):
    """Parse a `failed_reason` value into two components: an explicit
    failure reason, with which `fail()` would have been called, and a
    sequence of object class+ID identifiers reflecting the order in
    which they were failed as part of a cascading failure.
    """
    trigger, *ancestors = reason.split('->')
    return {
        "original_reason": trigger,
        "chain": ancestors
    }

def test_failed_reason_parser(self):
    from dallinger.models import parse_failed_reason as subject

    assert subject("Boom!") == {"original_reason": "Boom!", "chain": []}
    assert subject("Boom!->Network1") == {
        "original_reason": "Boom!",
        "chain": ["Network1"],
    }
    assert subject("Boom!->Network1->Node1") == {
        "original_reason": "Boom!",
        "chain": ["Network1", "Node1"],
    }
    assert subject("Boom!->Network1->Node1->Vector1") == {
        "original_reason": "Boom!",
        "chain": ["Network1", "Node1", "Vector1"],
    }
    assert subject("->Network1->Node1->Vector1") == {
        "original_reason": "",
        "chain": ["Network1", "Node1", "Vector1"],
    }
```

**Comment by jessesnyder** [comment]
@pmcharrison Since you'd mentioned max size, I checked. I think 1 GB should be safe?

![PostgreSQL_TEXT_Data_Type_-_Features__Examples_and_Equivalents_-_SQLines](https://user-images.githubusercontent.com/63560/104530088-10de0680-55c0-11eb-897f-8dfd254d9f08.png)

**Comment by pmcharrison** [comment]
Haha yes :-)

**Comment by skleinfeldt** [comment]
@jacobyn This is in the Released column of https://github.com/Dallinger/Dallinger/projects/10, can it be closed?

**Comment by pmcharrison** [comment]
yes, thanks Sally!
________________________________
