### ISSUE TITLE
Defining a custom participant class: 2pt

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2258]
It is currently supported to customise all of the Dallinger classes except for the Participant class. In our work we have been forced to customise the Participant class in a hacky way that throws SQLAlchemy warnings and seems a little dangerous. This issue proposes making an official mechanism for specifying a custom Participant class as part of experiment.py.

**Comment by jacobyn** [comment]
@pmcharrison can you give an example of how the "hacky" solution look like? The developers were not clear about it.

**Comment by pmcharrison** [comment]
Yes, the hacky solution is just to create a new class called `Participant` in experiment.py that subclasses the Dallinger `Participant` class, and has the same SQLAlchemy polymorphic identity. This throws an SQLAlchemy warning, because you are writing over the previous Participant class. Then, whenever a participant is loaded from the database, it is instantiated using your custom `Participant` class rather than the original Dallinger one. It feels like a hack because a) the functionality depends on the import order, b) there is an SQLAlchemy warning (though we could suppress that), and c) custom logic in the participant `__init__` function won't be called.

**Comment by alecpm** [comment]
It seems like the simplest and most flexible solution here would be to update the `experiment_server.create_participant` route to delegate the actual participant creation to a method of the experiment class. So instead of a call like `participant = models.Participant(...)` it would do something like `participant = exp.create_participant(...)` where the new `dallinger.experiment.Experiment.create_participant` method would just do the same call by default, perhaps using a class attribute to determine the participant class internally.

**Comment by pmcharrison** [comment]
That would be perfect! Thank you.

**Comment by alecpm** [comment]
See PR #2324
