### ISSUE TITLE
Configuring when qualifications are assigned: 3pts + 5pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2261]
Currently experiment qualifications are automatically assigned when someone finishes the experiment (though not when they return it). However, in some situations (e.g. preventing people from taking any part of the experiment twice), it would be preferable to assign the experiment qualification instantly upon participant creation. We propose adding a new config.txt variable that can enable this behaviour (but leaving the default behaviour the same).

**Comment by thomasmorgan** [comment]
I'd be inclined to make immediate assignment the default. I imagine most users wouldn't want users who returned a hit to come again.

**Comment by pmcharrison** [comment]
Yes, though if you use qualifications to qualify people for follow-up experiments, then qualifying at the end would still be useful? Not sure it's wise to break back-compatibility by changing the default here?

**Comment by thomasmorgan** [comment]
In this case I suggest adding two config options for assigning qualifications: `qualification_on_accept` and `qualification_on_submit` as this is more explicit and allows users to assign qualifications at both points in a single experiment. We can keep the current thing for backwards compatibility, but going forward should have this split approach.

**Comment by pmcharrison** [comment]
Interesting idea, so in summary we would have three parameters:

- `assign_qualifications`
- `qualification_on_accept`
- `qualification_on_submit`

But then there is a decision to make about what takes precedence, `assign_qualifications` or the other two functions... Are you sure this is intuitive? as opposed to

- `assign_qualifications`
- `qualification_point` # default=start

where back-compatibility is maintained and there is no confusion about precedence.

**Comment by thomasmorgan** [comment]
I suggest we basically deprecate `assign_qualifications` as it is superseded by the other two. However we may wish to keep it (albeit hidden) for backwards compatibility. If we are going to allow qualifications to be assigned at different points it only makes sense that we also allow a single experiment to assign qualifications at *both* points, which wouldn't be possible with `assign_qualifications` and `qualification_point`. I also think that `qualification_on_accept` and `qualification_on_submit` are more explicit and easier to understand.

**Comment by pmcharrison** [comment]
Sure, makes sense :-) Just regarding this comment:

> If we are going to allow qualifications to be assigned at different
points it only makes sense that we also allow a single experiment to assign
qualifications at both points

Do we then need to update config.txt to allow the user to specify two
separate qualifications that will be assigned at these two points?
Presumably it's pointless to assign the same qualification twice, which
would currently be the default?

**Comment by thomasmorgan** [comment]
I'm not 100% sure I follow. But yes, for every qualification users want to assign to participants they need to decide if they want to assign it at the start or end of the experiment in which case they can add it to `qualification_on_accept` or `qualification_on_submit` respectively. In no case should they add it to `assign_qualifications` as that should be deprecated/hidden. That's my suggestion anyway.

**Comment by thomasmorgan** [comment]
Though it's not clear to me whether `qualification_on_submit` should apply to all submissions or only submissions that pass the data/attention checks...

**Comment by pmcharrison** [comment]
To paraphrase: you said

> it only makes sense that we also allow a single experiment to assign qualifications at both points

but this didn't make sense to me, because once you've assigned the qualification at the start, assigning the qualification again at the end would have no effect.

**Comment by thomasmorgan** [comment]
Ah yeah, I was referring to different qualifications. So you could, for instance, assign a blacklist qualification upon acceptance to stop the participant taking part again, and a whitelist qualification upon successful submission to grant the participant access to a follow up experiment. Something like that.

**Comment by thomasmorgan** [comment]
Also, the more I think about it, the `qualification_on_submit` should only be for successful submissions, so, to be explicit, it should probably be called `qualification_on_successful_submission` or a name to that effect.

**Comment by pmcharrison** [comment]
> Ah yeah, I was referring to different qualifications. So you could, for instance, assign a blacklist qualification upon acceptance to stop the participant taking part again, and a whitelist qualification upon successful submission to grant the participant access to a follow up experiment. Something like that.

Yes, exactly - so it means we need to think about how the user can provide this information (previously `assign_qualifications` was Boolean, but presumably these new variables need to be integers or strings to accommodate custom qualifications).

**Comment by thomasmorgan** [comment]
Was `assign_qualifications` boolean? I thought it was a comma separate list of qualifications to assign. Either way, yes, variables likes `qualification_on_accept` should probably be comma separated lists of qualification names. Though maybe we need ints for the qualification values too? I don't know, we can figure out the precise details. The goal is just to allow experimenters to assign different qualifications following different events. A more flexible system may be best.

**Comment by pmcharrison** [comment]
I never used it myself, but it seems that way from the source code: 

![Screenshot 2020-12-07 at 17 02 58](https://user-images.githubusercontent.com/22684998/101380936-0f793a00-38ae-11eb-8950-95d6526a886a.png)

I agree, something flexible and easily extensible would be good. I guess if we want something flexible, maybe it's easiest to do it in the Experiment class, but on the other hand config.txt seems to be a natural home.... So maybe some kind of string in the config.txt is best after all.

**Comment by jessesnyder** [comment]
@pmcharrison @thomasmorgan This has evolved a lot since we initially discussed it and assigned an estimate, and to be honest I'm sort of going in circles thinking about what to do, because it calls into focus some basic tensions within Dallinger's design and how it's evolved. I'd call the two main directions the "Psiturk Philosophy" (we're an opinionated wrapper around MTurk) and the "ExperimentClass Puppet Master Philosophy", which is the directly things have moved more recently.

In case it's not clear how this currently works, I'll summarize:
1. (digression) First, nothing ever happens unless you're using the MTurkRecruiter, because none of the other recruiters support qualifications. My instinct in the past has been to keep half an eye on the possibility that this may change, in which case we have an incentive to treat qualification assignment as a generic concept. This creates some friction with the "oh, come on.. we know it's MTurk... let me just do what I want" approach. We could just toss this aside, and let the experiment use its reference to the recruiter to give it orders. In this scenario, the Experiment takes on both the luxuries and responsibilities of knowing the recruiter details and managing things. Moving on to the description of the status quo...
2. The recruiter is called when the `assignmentSubmitted()` JS function is called, (via the `/worker_complete` route). 
3. If `assign_qualifications` is False (the default in `local_config_defaults.txt`), no qualifications will be assigned, period. The recruiter method just returns.
4. If `assign_qualifications` is True, the MTurkRecruiter will assign at least one qualification with the ID of the experiment run, and an additional one using the config's `group_name` value.

One avenue consistent with the Experiment Puppet Master approach that might give you a lot of control without leaking too much recruiter implementation specifics (the enemy of being able to support pluggable recruiters):

When a Participant is added to a Node (are there experiments that use Participants without Nodes? I should probably know, but have forgotten...), the experiment is called afterwards:

```python
@app.route("/node/<participant_id>", methods=["POST"])
@db.serialized
def create_node(participant_id):
    """Send a POST request to the node table.

    This makes a new node for the participant, it calls:
        1. exp.get_network_for_participant
        2. exp.create_node
        3. exp.add_node_to_network
        4. exp.node_post_request
    """
    exp = Experiment(session)

    # blah blah blah...

    # ping the experiment
    exp.node_post_request(participant=participant, node=node)  # <-- Here!!
```

We could add a public method no the recruiter where you could just assign qualifications directly.  We'd need to sort out whether this bypassed the `assign_qualifications` flag or not, but being able to support this sort of flexibility is the reason we added these callbacks. 

We could make experiment completion work similarly: stick a call to the experiment in between the `/worker_complete` route and the recruiter, so it was the _experiment_ which optionally called the recruiter to add qualifications. Since qualifications are just strings, there's not much implementation detail to hide here, and the recruiter's interface still feels relatively generic.

**Comment by thomasmorgan** [comment]
Thanks Jesse.

In general I think we should move towards the puppet master approach, even if it feels kinda weird because MTurk is the only fleshed out recruitment service right now. It seems intuitive to me that config could support lists of qualifications to assign at semi-prespecified points and these are passed on to the recruiter and the recruiter implements then as best it can (even if some recruiters just print a warning saying you've asked for qualifications to be assigned, but the recruitment service you have chosen doesn't support them).

Precisely what these points are is up for debate. Participant creation is certainly an option, though as you note this might not actually be that meaningful. Whether node creation is a better measure of a participant meaningfully taking part is not totally clear to me (but I don't think any current experiments involve node-less participants), especially as some experiments I run that have waiting rooms create Nodes at the start of the waiting room, so its no more informative that participant creation in that case. I wonder if we could open up an experiment method to users to define the criteria for "meaningful participation", this could certainly default to node creation. A final point would be experiment completion (and we could discuss whether submissions that fail data/attention checks should be included, my gut is they should).

I also think that a method to assign qualifications at any point is a good idea.

Also, if there a reason that qualifications are in config.txt instead of experiment.py? The recruiter is set in experiment.py right? It feels intuitive that these should be in the same place.

Anyway, so here's what I am imagining an experiment might look like:

```
self.recruiter = MTurk
self.qualifications_on_recruitment = None
self.qualification_on_participation = ["MyQualification7651", "MyOtherQualification1234"]
self.qualification_on_completion = "YetAnotherQualification7777"

def participation_check(self, participant):
    if not participant.nodes():
        return False
    return len(participant.nodes()[0].infos()) > 0

def info_post_request(self, node, info):
    # blah blah blah

    if len(node.infos() > 10):
        self.assign_qualification(node.participant, "10InfoQualification"
```
What do you think? I am a little uneasy about this system not having unqiue qualifications for every deployment, but users can turn that off anyway with the current system.

**Comment by jessesnyder** [comment]
Thanks, @thomasmorgan This does feel like the more promising path. I've started a PR to continue the conversation:
https://github.com/Dallinger/Dallinger/pull/2548
