### ISSUE TITLE
Dashboard lifecycle links are wrong: 1pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2270]
![image](https://user-images.githubusercontent.com/10518584/88172363-267dff00-cc21-11ea-9276-2726cf170af4.png)

The lifecycle links seems to have the wrong values:
this is what shows up:

`dallinger destroy --app 10d52bb7-9fb2-d9a6-7df3-388e6045e5d8`

But the real app name was:
```
❯❯ Experiment details:
App home: https://dlgr-nor2test.herokuapp.com
Dashboard URL: https://dlgr-nor2test.herokuapp.com/dashboard/

```

so clearly a bug.

**Comment by jessesnyder** [comment]
The problem only occurs when a custom experiment ID is specified when calling `dallinger deploy` or `dallinger sandbox`. 

The underlying cause is that the Heroku app is created using the custom ID (potentially truncated, and with `dlgr-` prepended to it), but then the custom ID is not recorded anywhere within Dallinger. When the Lifecycle dashboard generates CLI commands, it assumes no custom ID has been provided and uses the auto-generated experiment UID when calculating commands.

The auto-generated UID is used internally throughout most Dallinger even when a custom one is provided; a brief scan of the code base indicates that the _only_ place the custom ID is used may be in generating the Heroku app. If this is indeed the case, and having a customizable Heroku ID is valuable --personally I'd find it confusing to deal with two IDs; there's no avoiding the auto-generated UID since it's used everywhere else-- we can probably fix this by recording the custom ID as a config variable, but things would definitely be simpler without the custom IDs.

**Comment by jacobyn** [comment]
I think the custom ID is an important feature. Storing it as a config variable does not seem problematic to me.
