### ISSUE TITLE
Monitor route do not show the participants on the edges and do not color the nodes in the right way: 2pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2273]
[this is related to #2220]
The two features in  #2220

12. Indicating the participant number on edges
10. Coloring nodes.

Do not work well. For example:

![image](https://user-images.githubusercontent.com/10518584/88176696-f25a0c80-cc27-11ea-8fe6-6d6d19e9b876.png)

participant are not indicated the way they should according to 10 and 12 in #2220 
 
Like this:
![image](https://user-images.githubusercontent.com/10518584/88176724-fede6500-cc27-11ea-8b3c-c279a2b5d03e.png)

**Comment by alecpm** [comment]
When testing and developing, I noticed that when using the `non_adaptive` demo that the `participant_id` for nodes was being set to `null` in all scenarios I was able to test. It seems like this might be an issue with some aspect of the experiment or configuration (or possibly the `network_structure` or `__json__` output). I did see the participant indications and colors when testing with other experiments.

@jacobyn could you confirm that participant ids are actually being set on the Nodes in the scenario shown in the first graph? When I checked the sandbox and live experiment dashboards that you shared with me, it looked like the nodes and infos had `null` participant ids just as I had seen with the `non_adaptive` demo in testing.

**Comment by pmcharrison** [comment]
That’s right, in the non-adaptive demo the participant ID of the node is
always null. In this case we need to fall back on the node colouring rules
specified in #2220, colouring nodes based on the connected infos.

**Comment by alecpm** [comment]
This turned out to be a little tricky because the rules were being followed for experiments with `participant_id` assigned to the Nodes. However, the psynet experiments sometimes have a `null` `participant_id` on the `Node` and record the `participant_id` as a string in `property1` on the `Info` objects. This isn't something that we can account for generically within Dallinger, but if the JSON representation of such an `Info` includes a `participant_id`, the code now treats it per the rules in #2220 including transferring the color back to the connected `Node`. This is implemented in PR #2279. To see it work for the psynet non_adaptive Experiments, the following custom method would need to be added to the `NonAdaptiveTrial` class:

    def json_data(self):
        data = super(NonAdaptiveTrial, self).json_data()
        try:
            data['participant_id'] = int(self.property1)
        except (ValueError, TypeError):
            pass
        return data

That will add a `participant_id` value to the JSON data used for the Network Monitor and Database views, which will be used for node coloring when the connected `Node` does not have an associated participant. Hopefully, it is somewhat obvious how one would accomplish the same thing for other experiment designs that store a `participant_id` in a such a non-direct manner. Alternatively, you could add a `participant_id` database attribute to your custom `Info` sub-class, which should also be supported by the changes in the network monitor script.

**Comment by jacobyn** [comment]
Hi Alec, Thank you for accommodating these different implementation choices. I am very content with your proposal that looks very logical to me.
