### ISSUE TITLE
Adding a random letter in the title when deploying a HIT: 1pt with repeated title

### ISSUE THREAD

**Issue by mangl001** [Dallinger/Dallinger#2310]
When deploying an app that has the same title of an existing running app, Amazon mTurk seems to get confused and we have issues with bonus payments and the expiration of HITs. It is easy to make this mistake when someone is working in the same experiment and deploys it multiple times with small variations.

This issue proposes a functionality that checks whether an app is being deployed  with the same title of an existing deployed app, and if true, then it adds a random letter in the title to avoid this problem.

**Comment by jacobyn** [comment]
One thought here. One way to implement it will be to add to the title some structured string like  "<app-name>". In deploy time this will be replaced by another string. The advantage of this that this perhaps can  be used more generally for example we may add <date> (no need to implement it now, just explaining why this is more general). The same logic can allow easy customization of the title as well (we can have a title like "Listen to pitches and melodies and sing them back (bonus up to approx. $<bonus>!" )  instead of "Listen to pitches and melodies and sing them back (bonus up to approx. $3.30!)".  This is a suggestion, I am also OK with implementing this issue in a simpler way.

**Comment by pmcharrison** [comment]
In this case I think there should also be an automated check to make sure that the app title is not already taken?

**Comment by jessesnyder** [comment]
We should settle on a format for the title, since I got a little lost in the above debate.

Proposal to throw darts at:
"{title from configuration} ({short version of app ID})"

Example:
"War of the Ghosts (dlgr-74b4b9a9)"

**Comment by pmcharrison** [comment]
Your proposal sounds ideal, @jessesnyder. I am happy to settle on that.
