### ISSUE TITLE
Dashboard: MTurk tab does not work: 5pt

### ISSUE THREAD

**Issue by mangl001** [Dallinger/Dallinger#2373]
Using Dallinger 6.5.0, the MTurk tab in the dashboard does not work. 

Each time that I try to click on the "mTurk" tab there is an application error and it throws a timeout [error.[](url)](url)
<img width="1481" alt="Screenshot 2020-09-17 at 16 05 13" src="https://user-images.githubusercontent.com/33897368/94915636-86a8e100-04ad-11eb-8dca-5716fefdafa6.png">
<img width="1206" alt="Screenshot 2020-09-17 at 16 05 25" src="https://user-images.githubusercontent.com/33897368/94915645-89a3d180-04ad-11eb-9c66-3487699a43f2.png">

I can share the logs of an app showing this problem.

**Comment by jacobyn** [comment]
This seems to relate to the new changes in 6.5.0.

**Comment by jessesnyder** [comment]
The issue here is a result of our new [attempt at] support for multiple HITs per experiment with the `--archive` option to `dallinger deploy`/`dallinger sandbox`. If you're using an AWS account with lots of HITs registered, we time out trying to identify the current HIT related to the experiment. Realistically, we will need to switch to storing this current HIT info locally (in redis, probably).

**Comment by pmcharrison** [comment]
Thanks, Jesse! I'll let the others know that we need to clean out the HITs.

**Comment by pmcharrison** [comment]
@jessesnyder , is it necessary to actually delete the HITs, or is expiring them sufficient, do you think?

**Comment by jessesnyder** [comment]
@pmcharrison We're relying on the ListHITs API, which returns all non-deleted HITs, and accepts no filtering/search parameters, maddeningly. So, yes, they'd need to be deleted rather than just expired.

https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListHITsOperation.html

For this reason, I think we probably need to solve this another way: by storing the current HIT ID in redis, rather than querying for it, as I mentioned in the previous comment. :-(

**Comment by pmcharrison** [comment]
Thanks for explaining, @jessesnyder ! We'll make sure to allocate time for this Redis solution in the next contract :-)
