### ISSUE TITLE
Dallinger incompatible with default redis version provided by Heroku

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#2436]
## Expected Behavior
Dallinger deploys and works as expected on non-hobby dynos.

## Current Behavior
It does not deploy on non-hobby-grade dynos due to Heroku upgrading Redis dynos to Redis 6 recently. It seems likely to work with Redis 5, based on conversations with Heroku staff and testing the various redis commands in Dallinger's codebase on Redis 5.

## Steps to Reproduce (for bugs)
Attempt to launch any Dallinger experiment on non-free dynos.

## Your Environment
Dallinger 6.5.0, Ubuntu 18.04. Also tested on the same on elementaryOS (which is built on Ubuntu).

**Comment by stefanuddenberg** [comment]
## Expected Behavior
Dallinger deploys and works as expected on non-hobby dynos.

## Current Behavior
It does not deploy on non-hobby-grade dynos due to Heroku upgrading Redis dynos to Redis 6 recently. It seems likely to work with Redis 5, based on conversations with Heroku staff and testing the various redis commands in Dallinger's codebase on Redis 5.

## Steps to Reproduce (for bugs)
Attempt to launch any Dallinger experiment on non-free dynos.

## Your Environment
Dallinger 6.5.0, Ubuntu 18.04. Also tested on the same on elementaryOS (which is built on Ubuntu).

**Comment by jessesnyder** [comment]
Thanks, @stefanuddenberg! I copied your summary into the main issue description.

**Comment by pmcharrison** [comment]
This worked great. Thanks!
