### ISSUE TITLE
Generic recruiter: customised entry point: 5pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2464]
Related to #2465
In our new generic recruiter, we want the participant's entry to the experiment to work in the following way:

* There is one fixed link that we send participants to if they want to start the experiment. This link may carry URL parameters that give us information about the participant. The link might look something like this: `https://my-app.herokuapp.com/ad?participant_code=xyz&region=us&...`.
* These extra URL parameters are saved in a new participant field, `participant.entry_information`.
* We can add a customisable method, `experiment.validate_entry_information()`, which allows us to check this entry information, for example to block participants with invalid entry codes.

**Comment by jacobyn** [comment]
Perhaps this task should also include instantiating a new type of recruiter class ("generic recruiter").

**Comment by alecpm** [comment]
Jesse and I spent some time discussing this and we agree that a new base recruiter class is probably a good idea here. We also thing that it might make sense to delegate some functionality to the recruiter instead of having it all in the experiment.

My initial thought is that perhaps the experiment server or experiment could pass the `entry_information` data to a method on the recruiter (which presumably understands that data in some way) which would transform that data into identifiers for the experiment (used for `hit_id`), assignment (used for `assignment_id`) and person (used for `worker_id`). Perhaps the experiment could delegate part of the default `validate_entry_information` call to this recruiter method as well (since in the general case the recruiter is what understands these recruitment related variables).

It's not quite clear to me how this would all be handled for a completely generic recruiter, but I'll be starting the implementation for review shortly.

**Comment by alecpm** [comment]
Proposed CHANGELOG entry:

* Added new `entry_information` column to `Participant`, along with mechanism for entering an experiment with assignment data different from the standard MTurk HIT parameters. This should provide flexibility to allow for a variety of custom recruiters.
