### ISSUE TITLE
entry_information not stored owing to bug in dallinger2.js

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2652]
Extra URL parameters are meant to be stored in `Participant.entry_information`. Currently this fails (tested with the bartlett1932 demo).

The error appears to be in `dlgr.createParticipant`:

``` js
  dlgr.createParticipant = function() {
    var url = "/participant";
    var data = {};
    var deferred = $.Deferred();

    if (dlgr.identity.assignmentId) {
      url += "/" + dlgr.identity.workerId + "/" + dlgr.identity.hitId +
            "/" + dlgr.identity.assignmentId + "/" + dlgr.identity.mode + "?fingerprint_hash=" +
            (dlgr.identity.fingerprintHash) + '&recruiter=' + dlgr.identity.recruiter;
    } else {
      data = dlgr.identity.entryInformation;
    }
...
```

Looking at this, we see that if `dlgr.identity.assignmentId` is truthy, then the URL is constructed from `dlgr.identity`, ignoring the entry information. 

We therefore have a hack in our own code that temporarily sets `dlgr.identity.assignmentId` to `null` to avoid this behaviour:

``` js
{% block scripts %}
{{super()}}
    <script>
        dallinger.identity.participantId = "undefined";

        let assignmentId = dallinger.identity.assignmentId;
        dallinger.identity.assignmentId = null;

        dallinger.createParticipant().done(function(resp) {
            setTimeout(function() {
                let participantId = dallinger.identity.participantId;
                dallinger.identity.assignmentId = assignmentId
                dallinger.goToPage("timeline/" + participantId + "/" + assignmentId);
            }, 500);
        }).fail(function(resp) {
            dallinger.error(resp);
        });
    </script>
{% endblock %}
```

However, I believe that the issue should really be addressed in `dallinger2.js`. I don't really understand the logic for why there are two versions of the URL construction procedure depending on whether `dlgr.identity.assignmentId` is initialised or not, but in any case, the logic between these two versions should be consistent.

Perhaps it would be worth additionally adding a test to ensure that entry_information really is registered properly?

**Comment by jessesnyder** [comment]
@pmcharrison This is almost certainly a whac-a-mole side-effect of https://github.com/Dallinger/Dallinger/pull/2609, but I'm not immediately clear about how to fix it. The truthy-ness of `assignmentId` clearly signifies something very important, but it's completely implicit and undocumented, and whatever it is, we should make it explicit in the course of fixing this.

**Comment by jessesnyder** [comment]
@pmcharrison Maybe the idea was that if you're using `entryInformation` you're using it _instead of_ the "traditional" (MTurk) parameters? I think @alecpm will have our answer, actually.

**Comment by alecpm** [comment]
I think the idea was that `assignment_id` in the initial request meant that you were using the new `entryInformation` approach and `assignmentId` in the request initiated the old approach. That is a bit implicit, but the intent was to provide a new way while providing backwards compatibility. Not sure what the best fix would be beyond using `assignment_id` in the ad urls in experiments that want to use the `entryInformation` approach.

**Comment by pmcharrison** [comment]
Thanks for explaining, @alecpm. Personally, I'm not so keen on the idea of using snake case vs camel case as a way of differentiating the approaches. It just feels like a mistake when you read the code (as @jessesnyder and I found!)

I didn't appreciate yet why this is needed for backward compatibility, though. I understand that, previously, extra URL parameters would simply be ignored. In @alecpm's proposal, we still ignore URL parameters if people are using the old-style URLs with camel case `assignmentId`, but if people are using new-style URLs without camel case `assignmentId`, then the extra parameters are stored in `entryInformation`. My question is, why not always store the extra parameters in `entryInformation`? Not sure what we lose here.

**Comment by jessesnyder** [comment]
Minor correction: we do always store all parameters in `dallinger.identity.entryInformation` (the JS object), but we don't pass this value to `create_participant()` unless `assignmentId` is absent.

**Comment by jacobyn** [comment]
Note that in `advertisement()` within `experiment_server.py`. if we try the "new" way where `assignmentId` is not there, then there is an error occur:
```
 if not (hit_id and assignment_id):
        raise ExperimentError("hit_assign_worker_id_not_set_by_recruiter")

``` 
Rendering the "new" way - impossible without a hack. I think this should have been solved.

**Comment by jacobyn** [comment]
The use case for this feature was a recruiter class with a specialized  type of URL in the ad, something like this:
`ad?recruiter=myrecruiter&myInformation=12345`
The hope was that you can customize `normalize_entry_information` so that it digest this new type of information.

In reality this has several problems: 
a) If you don't include `worker_id`, `hit_id`  and `session_id`  dallinger backend complains, for example the participant class seems to ask for these values.
b) If you include `worker_id`, `hit_id`  and `session_id`  then it is discarded by the way ` dallinger.createParticipant = function()` is implemented. It seems that this should be changed in a way that allow to store always participant information like Peter's suggestion.

**Comment by alecpm** [comment]
I'm reviewing the code and tests, and I'm a little perplexed why this isn't working. The specification is that the `normalize_entry_information` method on either the recruiter or the experiment class should take a dictionary of arbitrary keys and values (derived from the request by default) and return a dictionary with `assignment_id`, `worker_id`, and `hit_id` keys set along with an optional `entry_information` key containing any additional data derived from the original dictionary.

The default implementation takes the values from the submitted `assignment_id` or `assignmentId`, `worker_id` or `workerId`, and `hit_id` or `hitId` respectively, and then puts any additional keys/values into the `entry_information` key. Those values are all passed to the participant constructor which stores the `entry_information` in a JSONB column.

I think the problem is that there's a bit of Javascript code that bypasses all this machinery when the original request (from e.g. `/ad` includes a url parameter `assignmentId`. If the request uses `assignment_id` instead (or some set of arbitrary keys that doesn't include `assignmentId`) you should get all values output as `entry_information` by the `normalize_entry_information` methods saved on the participant `entry_information`.

I could try getting rid of that bypass which was intended to preserve existing behavior with default MTurk URLs, but that may have been unnecessary. However, it should be possible to use this functionality currently by using an `/ad` url that doesn't include an `assignmentId`. It might make sense to update the default ad route's `generate_token` behavior to use the `assignment_id` spelling instead of `assignmentId`, so that it doesn't trigger the bypass by default. That probably isn't the issue though, since the randomly generated `assignment_id` url wouldn't include any `extra_information` in any case.

**Comment by fmhoeger** [comment]
To reproduce the issue, run a Dallinger demo experiment and inspect the `participant` table. The `entry_information` column contains no data.

**Comment by alecpm** [comment]
@fmhoeger As noted above, the additional `entry_information` is saved only when `assignmentId` isn't included in the ad/consent urls. I used a url like the following:

http://127.0.0.1:5000/consent?recruiter=hotair&hitId=ZCSK7A&assignment_id=2TH56D&workerId=BRSJOY&test_value1=1&test_value2=2

On a local run of bartlett1932 and the data was saved:

<img width="920" alt="Screen Shot 2022-01-26 at 8 27 43 AM" src="https://user-images.githubusercontent.com/202854/151204271-5d581f39-a625-42b9-9d6c-0a0320cf0f12.png">

This also won't work if your browser local storage already has an `assignmentId` value set, but that shouldn't be the case normally.

**Comment by jacobyn** [comment]
@frank It seems that we missed what was written in the documentation: https://dallinger.readthedocs.io/en/latest/the_experiment_class.html#dallinger.experiment.Experiment.normalize_entry_information

**Comment by jessesnyder** [comment]
I'm wondering if we should raise an error any any route that calls `exp.normalize_entry_information()` if the return value doesn't fulfill the contract, rather than shuffling on and failing in various ways later?

**Comment by fmhoeger** [comment]
@alecpm I tried it again with this URL `http://localhost:5000/ad?recruiter=hotair&assignment_id=XOB51N&hitId=QPTOFI&workerId=FZSVK0&mode=debug&test=123`.
The problem persists, `entry_information` is left empty (`{}`). I checked local storage and found the information in the screenshot attached. 
![entry_info](https://user-images.githubusercontent.com/59626853/151252690-f6396693-8d11-4de2-8818-c9a1e77ce32f.png)
![local_storage](https://user-images.githubusercontent.com/59626853/151252694-1645241b-619a-4bbb-b21e-53126868a07a.png)
