### ISSUE TITLE
Dallinger deploy from docker image

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2807]
We want to be able to add an extra optional argument to the `dallinger deploy` command that allows us to specify a custom Docker image as the source code for the deployment. This Docker image would be used instead of using the local experiment directory, as is done currently. This would be very helpful for long-term scientific reproducibility.

**Comment by silviot** [comment]
@pmcharrison when using this new optional argument the directory dallinger is invoked from will be irrelevant (as opposed to the usual `dallinger deploy` that defauts to the current directory).

**Comment by silviot** [comment]
#2754 now allows one to deploy a docker image from a public registry:
```
dallinger docker deploy-image --image ghcr.io/dallinger/dallinger/bartlett1932@sha256:eaf27845dde7dc74e361dde1a9e90f61e82fa78de57228927672058244a534a3
```
The total time is on average two minutes.

The code that does the deployment is almost entirely new: instead of the command line client the API is used, via the `heroku3` package.

The user running the command does not need docker installed on their machine.

For now there's no way to scale up the deployment. That part of the configuration is currently stored inside the experiment, but in this case we have a docker image identifier. My plan is to let the user override settings from the command line.

The redis add-on is currently [`redistogo:nano`](https://elements.heroku.com/addons/redistogo) (only when deploying with this command).
