### ISSUE TITLE
Database display in dashboard seems to have been compromised

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#2954]
On the latest version of Dallinger, the database display in the dashboard seems to be a little less well-formatted than we remembered it, in the mcmcp demo (at least). It looks normal in the bartlett1932 demo, though--

<img width="1569" alt="Screenshot 2021-05-27 at 12 16 30" src="https://user-images.githubusercontent.com/22684998/119817042-6074fd00-bee5-11eb-918f-6d1ef8c5eed8.png">

Is it possible that some dependency has changed, or is not loading properly?

<img width="210" alt="Screenshot 2021-05-27 at 12 16 50" src="https://user-images.githubusercontent.com/22684998/119817076-6bc82880-bee5-11eb-9e40-3786e33ee24d.png">

**Comment by jacobyn** [comment]
@alecpm  as of our discussion today, we are hoping that you can also work on #3034 (adding the notification table to the dashboard) while finishing this issue. It would be amazing if we can add it too.

**Comment by alecpm** [comment]
@pmcharrison The fix for MCMCP (and likely any other experiments seeing this issue) is to remove the `boostrap.min.css` provided by the experiment (in `static/css/bootstrap.min.css`). MCMCP includes bootstrap 3.3.1, but Dallinger provides and expects Bootstrap 4.5.x, which is why certain elements aren't styled correctly.

I'm reluctant to remove the MCMCP bootstrap myself, because there may be aspects of the experiment that rely on Bootstrap 3 CSS classes. Someone more familiar with that experiment should probably test it without the included bootstrap.min.css and ensure it still looks as expected. I suspect it will not require many if any changes, but there's a guide to changes [here](https://getbootstrap.com/docs/4.0/migration/#by-component).
