### ISSUE TITLE
Silviot and Jesse discuss way forward for #3184 and #3145

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#3345]
Silviot and Jesse discuss way forward for #3184 and #3145 and decide what they want to do (potentially even pointing the issues).

**Comment by jessesnyder** [comment]
In update_experiments_constraints.sh, instead of invoking dallinger generate-constraints in each demo (except the Bartlett special case), we should instead directly run pip compile in each demo directory, specifying Dallinger's dev-requirements.txt file as a constraints file.

After releases are complete, the dallinger version should be bumped to the next minor version, plus the suffix `a1`, to indicate and alpha release. It should be possible to do this using https://pypi.org/project/bump2version/:

> For advanced versioning schemes, non-numeric parts may be desirable (e.g. to identify alpha or beta versions to indicate the stage of development, the flavor of the software package or a release name). To do so, you can use a [bumpversion:part:…] section containing the part's name (e.g. a part named release_name is configured in a section called [bumpversion:part:release_name].

If this configuration is hard to get right, a new version can be specified explicitly with the `--new-version` option.

We believe the proposed fix for #3184 can actually be tested using the proposed technique for #3145.
