### ISSUE TITLE
A participant's unique id exceeded 50 chars

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#348]
unique_id is a String(50) column in the Participant table.

Today this caused an error as a request to create a participant was received with a unique_id of u'A0384[redacted 16 characters]:3YOH7BII097S091VIWGYDU7IGJLVKI'. This is 55 chars long and so it wouldn't fit in the table.

It is trivial to allow longer strings in the table, but do we want to do this? I thought worker/assignment ids were of fixed length, in which case this probably indicates an error somewhere.

What do we think?

**Comment by suchow** [comment]
@thomasmorgan I don't see any issue with expanding it. We should be able to tell what happened by comparing these worker IDs and HIT IDs to ones from previous experiments. At least one of them must be longer.

(Also, don't paste worker IDs publicly because they are considered personally identifiable information. I've redacted your comment.)

@jacobyn I think you ran into the same issue?

**Comment by jacobyn** [comment]
I think that the reason for that is that users change the url or refresh the consent form in a way that changes the worker_id string. The code supposes take care of this (e.g by returning 404) instead of return a terminal error.

**Comment by thomasmorgan** [comment]
@jacobyn I wondered if that was the case too - it has happened before. However, this error has now happened a couple of times in the past few days and whereas before workers changed the worker id to something ridiculous (e.g. "ayyylmao") all recent instances have resembled normal AWS worker ids, they are just longer. Given that AWS has resumed development on MTurk and I have noticed it behaving in a couple of other unusual ways I think this might actually be a change in MTurk's policy on worker id length.
