### ISSUE TITLE
sphinx-js is blocking upgrade of several core packages

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#3776]
The `sphinx-js` package hasn't been updated for many months and also doesn't seem to be maintained very well. 
`Jinja2`, `Flask`, and a growing number packages are prevented from upgrading due to following constraint in `sphinx-js`:
`install_requires=['Jinja2>2.0,<3.0', 'parsimonious>=0.7.0,<0.8.0', 'Sphinx>=3.0.0']`

When removing `sphinx-js` from Dallinger all tests still run without error. 
Can `sphinx-js` possibly be removed from Dallinger without (severely) affecting documentation generation? 
This would allow for important packages like `Flask` and `Jinja2` to be upgraded to new major versions.

**Comment by jessesnyder** [comment]
We cannot trivially drop `sphinx-js` as a dependency because a large volume of generated JavaScript documentation depends on it.

We have added a [monkeypatch](https://github.com/Dallinger/Dallinger/blob/604d7d0592bdb20d2db13f5bdda0b1dd8a9a6a3a/docs/source/conf.py#L54) to allow the package to work with python 3.10, but the declared dependencies still block us from updating other dependencies (Flask, in particular), so we will need to continue to monitor this.

There is a [PR](https://github.com/mozilla/sphinx-js/pull/184) on the sphinx-js repository to address this.

**Comment by fmhoeger** [comment]
We have _temporarily_ removed the `sphinx-js` dependency in `v9.0.0` of `Dallinger` to be able to upgrade important libraries like `Jinja2` and `Flask` to their newest versions. There is also [this PR](https://github.com/mozilla/sphinx-js/pull/191) which should allow us to readd `sphinx-js` once the PR is merged and a new version of `sphinx-js` is released.
