### ISSUE TITLE
Allow disabling HTTP routes in experiment app: 5pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#4277]
`experiment_server.py` provides by default a collection of HTTP routes, e.g.

```
@app.route("/info/<int:node_id>/<int:info_id>", methods=["GET"])
```

which gets the JSON contents of a given info. These routes have no authentication protocols, which is problematic as they could be used to access sensitive participant data. In PsyNet we don't use these routes ourselves, but instead use our own collection of authenticated routes. However, these Dallinger routes still provide a backdoor to participant data.

The dream solution would be to add a proper authentication system for these routes. However this would be time-consuming to implement and not directly helpful for our own work. For now we would like to request instead something much simpler: the ability to optionally disable some of these built-in routes. 

A subtlety is that these routes are registered at import time, and I'm not sure it's easy to unregister a Flask route once it's registered. Maybe the best thing to do is to refer to config.txt when deciding whether to register a particular route?

**Comment by jessesnyder** [comment]
@pmcharrison Proof of concept for your early review:
https://www.screencast.com/t/wSQiMfi7h

tl;dw - Your route decorator proposal seems completely sound, and since the decorator is called at request time, we can count on config having been loaded via Flask's `@before_first_request` hook.

## Qs

- In the demo, I'm assuming the new config variable will be JSON. I think we've done this before. Seem OK?
- Would you prefer to return a 200 with a message like the demo, a completely opaque 404, or something else?

**Comment by pmcharrison** [comment]
Thanks @jessesnyder! Looking good so far. I proposed a little change to the location of the config loading and pushed it (see notes in PR). 

Regarding behaviour on accessing a disabled route, I think my instinct would simply be to raise a `RuntimeError` within the decorator, which will automatically result in a 500 error and a useful traceback in the Python logs. You could make an argument for customizing this to make it a 404 error but I'm not sure it's worth the extra lines of code. What do you think? The reason I prefer this to the current solution is that I think it'll be helpful for people when debugging.

**Comment by jessesnyder** [comment]
All of that makes sense to me.

**Comment by jessesnyder** [comment]
I was reminded `PermissionError` is a built-in exception type, and it seems like the right one here. It will presumably be the only one of these in the logs, so should be easy to isolate:

```
127.0.0.1 - - [25/Aug/2022 10:14:15] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/jesses/.pyenv/versions/3.10.2/envs/dallingerP3.10.2/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/jesses/projects/py_dev/Dallinger3102/dallinger/experiment_server/experiment_server.py", line 70, in if_enabled
    raise PermissionError(f'Call to disabled route "{current_route}"')
PermissionError: Call to disabled route "/"
```

**Comment by pmcharrison** [comment]
Perfect!

**Comment by jessesnyder** [comment]
@pmcharrison The [inevitable] complication:

In my prototype, the decorator compares `request.path` to values in the `disabled_routes` list, which works for simple routes which don't include interpolated path elements (`<int:node_id>`, etc.), but for complex routes, `request.path` includes the values from the request, so we can't match on that since it will vary with the IDs included in the URL:
```
(Pdb) request.path
'/info/1/1'
```

Instead, we can either match on the matching rule string:
```
(Pdb) request.url_rule.rule
'/info/<int:node_id>/<int:info_id>'
```

or the Python function/method name:
```
(Pdb) request.endpoint
'get_info'
```

## Rule string option
The rule string is more flexible, and probably more "correct", because although we don't do this in Dallinger currently, you can technically decorate the same Python function with more than one `@route` declaration:
```
@app.route('/item/<int:appitemid>/')
@app.route('/item/<int:appitemid>/<path:anythingcanbehere>')
def show_item(appitemid, anythingcanbehere=None):
```

It's conceivable that _if_ we had a function supporting multiple routes, you'd want to disable one route, but not the other.

## Endpoint/function name option
However, the endpoint/function name is more concise and easier to copy into a JSON array in config.txt.

What do you think?

**Comment by jessesnyder** [comment]
See also "Another argument..." above. (I edited the comment, which can be hard to track.)

**Comment by jessesnyder** [comment]
I ran with the Rule String option.

Another question, @pmcharrison: which routes in experiment_server.py should this new decorator be added to (or which should it _not_ be added to might be easier)?

**Comment by jessesnyder** [comment]
Also: should there be an "all" option that would disable all the routes that include the decorator?

**Comment by pmcharrison** [comment]
Hi @jessesnyder! I think the rule string choice makes sense, good arguments.

I think it is a little difficult to know which routes would never need to be disabled so I'd probably just add this functionality to all of them. However in that case I think it would be a bit perverse to have an "all" option, because then the app wouldn't be able to do anything.

I thought some more about it and wondered, maybe a succinct implementation would be to use Flask's before_request method, which would mean you don't have to add the decorator manually to each function?

**Comment by jessesnyder** [comment]
I felt like there was a missing piece, but my head has been out of Flask-land for a long time. I'll look at the before_request approach, since that sounds right.

**Comment by jessesnyder** [comment]
Hmm, I get old faithful:
```
RuntimeError: Working outside of request context.
```

It looks like `@before_request` may not give you access to the request, which we need (and this makes some sense). Looking for other hooks...

**Comment by jessesnyder** [comment]
Another thing that makes me think we have to use the decorator is that it's the customary way to require authentication for routes, or require specific permissions, etc. If you could use `@before_request`, you could list all the routes you wanted protected and do it in one place, which I haven't ever seen described.

**Comment by pmcharrison** [comment]
Ah I see. That's unfortunate! I saw this answer which made me think it was possible: https://stackoverflow.com/a/14368550

**Comment by pmcharrison** [comment]
I suppose patching app.route would be an ugly alternative....

**Comment by jessesnyder** [comment]
> I suppose patching app.route would be an ugly alternative....
Crossed my mind, I shuddered, and forced myself to think about something else.

I am confused by that SO post; maybe I'm missing something.

**Comment by jessesnyder** [comment]
I called in the big guns:

>miguelgrinberg
 — 
Today at 3:48 PM
The before_request handler does have access to the request object. This is actually the best way to implement what you need, since you can do it once and it applies to the entire application.

I had some other state-y problem or something that was causing the failure. It's working now.. Look Ma: no decorators!

**Comment by pmcharrison** [comment]
Excellent!
________________________________
