### ISSUE TITLE
Shut down automatically

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#529]
If an error occurs during launch, a Heroku app can be created an not killed. This issue may also happen by accident if somebody runs an experiment and forgets to kill it after running.

## Expected Behavior
Perform auto-shutdown after configurable time, to avoid Heroku money bleeding.

## Current Behavior
If you forget an app, it will bleed money forever.

**Comment by suchow** [comment]
Building on this, it would be good if apps automatically scale down and notify the experimenter if they haven't seen activity in a long time (e.g., 24 hours).

**Comment by vlall** [comment]
This has been discussed and it is not possible to destroy an app  from within itself. However, we do have a notification PR merged here: https://github.com/Dallinger/Dallinger/pull/773. 

If we need a system to monitor and destroy apps, we will need to have some intermediate process monitor apps. This may happen if we change the current architecture in the future. I will shelf and close this since an immediate solution has been merged.
