### ISSUE TITLE
Add Prolific development recruiter 

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#6715]
* Add new class `DevProlificRecruiter`

**Comment by jessesnyder** [comment]
The approach to isolation I took in tests of the `ProlificRecruiter` might also be helpful in this case: rather than mocking things out at a low level, I replace the `ProlificService` instance the `ProlificRecruiter` delegates to with a mock version. Maybe you could do the same thing, but with a version of `ProlificService` that logs? Being able to test the recruiter without calling real APIs was the main motivation for separating service and recruiter, and it seems like that separation could be used to advantage for your use-case.
